### ISSUE TITLE
`@props` formatting issues

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#17]
Input
```blade
@props([
    'foo' => [],
    'foobarbaz' => false,
])
```

Output
```blade
@props([
    'foo'       => [
    ],
    'foobarbaz' => false,
])
```

Expected input to remain unchanged.
Seems like a regression in 1.1.2, @JohnathonKoster?

**Comment by JohnathonKoster** [comment]
Will take a look; thanks!

**Comment by JohnathonKoster** [comment]
Regression fixed in `1.1.3` (with new test coverage)

**Comment by zepfietje** [comment]
Perfect!

**Comment by zepfietje** [comment]
Still getting issues with a similar (but little different) snippet:

```blade
@props([
    'foobarbaz' => true,
    'bar',
    'baz' => true,
])
```

Is formatted as:

```blade
@props([
    'foobarbaz' => true,
    'bar',
    'baz'       => true,
])
```

While I would expect the input to remain unchanged.
