### ISSUE TITLE
Styles indented every time formatter is run

### ISSUE THREAD

**Issue by zepfietje** [Stillat/blade-parser-typescript#45]
This is an issue that occurs when running the formatter on the Filament codebase.
I've simplified it to the minimal amount of code that reproduces the issue:

```blade
<style>
    :root {
        --foo: red;

        @if (true)
            --bar: blue;
        @endif
    }
</style>
```

Every time the formatter is run, the styles get indented:

```blade
<style>
    :root {
            --foo: red;

            @if (true)
                --bar: blue;
            @endif
        }
</style>

```

Running it again:

```blade
<style>
    :root {
                --foo: red;

                @if (true)
                    --bar: blue;
                @endif
            }
</style>
```

The original code really doesn't need any formatting at all.

**Comment by JohnathonKoster** [comment]
Corrected in `1.3.0` 🙂

**Comment by zepfietje** [comment]
Thanks, John.
I found the issue still occurs when the code is already indented/wrapped though:
```blade
<div>
    <style>
        :root {
            --foo: red;
    
            @if (true)
                --bar: blue;
            @endif
        }
    </style>
</div>
```

```blade
<div>
    <style>
        :root {
                    --foo: red;

                    @if (true)
                        --bar: blue;
                    @endif
                }
    </style>
</div>
```

**Comment by JohnathonKoster** [comment]
Oh that was a tough one; but got it `1.3.1` while preserving the existing test cases👍

**Comment by zepfietje** [comment]
Glad you got it working!
